PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
delete {
    ?s ?p ?o .
}
where
{
    ?s ?p ?o .
    filter(!contains(str(?s), "http://transformunify.org/ontologies/TURBO_"))
}
