PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
insert {
    ?s rdfs:subClassOf <http://www.geneontology.org/formats/oboInOwl#ObsoleteClass>
} where {
    ?s <http://www.w3.org/2002/07/owl#deprecated> ?o .
}
